language: go
sudo: false
install: true
matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=linux GOARCH=amd64 BINARY=onionbox-linux-amd64
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=linux GOARCH=arm64 BINARY=onionbox-linux-arm64
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=linux GOARCH=arm BINARY=onionbox-linux-arm
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=darwin GOARCH=amd64 BINARY=onionbox-darwin-amd64
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=darwin GOARCH=386 BINARY=onionbox-darwin-386
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=freebsd GOARCH=amd64 BINARY=onionbox-freebsd-amd64
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=freebsd GOARCH=386 BINARY=onionbox-freebsd-386
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=freebsd GOARCH=arm BINARY=onionbox-freebsd-arm
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=windows GOARCH=amd64 BINARY=onionbox-amd64.exe
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=windows GOARCH=386 BINARY=onionbox-386.exe
    - os: linux
      dist: xenial
      go: 1.11.x
      env: GO111MODULE=on GOOS=linux GOARCH=386 BINARY=onionbox-linux-386
before_script:
  - go get -u -a -v -x github.com/ipsn/go-libtor
  - CGO_ENABLED=1 go build -gcflags=-m -a -tags netgo -ldflags '-w -extldflags "-static"' -o ${BINARY} .
script:
  - go test -v ./...