language: go
go: 1.11.x
os: linux
dist: xenial
sudo: false
cache:
  directories:
    - ${TRAVIS_HOME}/gopath/src/github.com/ipsn/go-libtor

matrix:
  include:
    - name: linux-amd64
      env: GO111MODULE=on GOOS=linux GOARCH=amd64 BINARY=linux-amd64
    - name: linux-arm64
      env: GO111MODULE=on GOOS=linux GOARCH=arm64 BINARY=linux-arm64
    - name: linux-arm
      env: GO111MODULE=on GOOS=linux GOARCH=arm BINARY=linux-arm
    - name: darwin-amd64
      env: GO111MODULE=on GOOS=darwin GOARCH=amd64 BINARY=darwin-amd64
    - name: darwin-386
      env: GO111MODULE=on GOOS=darwin GOARCH=386 BINARY=darwin-386
    - name: freebsd-amd64
      env: GO111MODULE=on GOOS=freebsd GOARCH=amd64 BINARY=freebsd-amd64
    - name: freebsd-386
      env: GO111MODULE=on GOOS=freebsd GOARCH=386 BINARY=freebsd-386
    - name: freebsd-arm
      env: GO111MODULE=on GOOS=freebsd GOARCH=arm BINARY=freebsd-arm
    - name: windows-amd64
      env: GO111MODULE=on GOOS=windows GOARCH=amd64 BINARY=windows-amd64.exe
    - name: windows-386
      env: GO111MODULE=on GOOS=windows GOARCH=386 BINARY=windows-386.exe
    - name: linux-386
      env: GO111MODULE=on GOOS=linux GOARCH=386 BINARY=linux-386
    - name: android
      env: CGO_ENABLED=1 GO111MODULE=on
      install:
        - sudo apt update && sudo apt install android-sdk
        - sdkmanager ndk-bundle
        - go get -u -a -v -x github.com/ipsn/go-libtor
        - go get golang.org/x/mobile/cmd/gomobile
        - gomobile init
      before_script: gomobile bind -v -x -target=android -o ./onionbox-android.aar .

install: go get -u -a -v -x github.com/ipsn/go-libtor

before_script: CGO_ENABLED=1 go build -gcflags=-m -a -tags netgo -ldflags '-w -extldflags "-static"' -o onionbox-${BINARY} .

script: go test -v -race -bench -cpu=1,2,4 ./...

deploy:
  if: branch = master
  provider: releases
  api_key: "${GITHUB_PAT}"
  file: "onionbox-${BINARY}"
  skip_cleanup: true
  draft: true
  on:
    tags: true